using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

namespace Örnek.Services;

public enum UiLanguage
{
    Deutsch,
    Turkce
}

public sealed class LocalizationService
{
    private const string SettingsFileName = "ui-language.json";
    private readonly Dictionary<string, string> _de = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, string> _tr = new(StringComparer.OrdinalIgnoreCase);
    private readonly string _settingsPath;

    public static LocalizationService Instance { get; } = new();

    public event EventHandler? LanguageChanged;

    public UiLanguage CurrentLanguage { get; private set; } = UiLanguage.Deutsch;

    private LocalizationService()
    {
        var appFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Rechnung");
        Directory.CreateDirectory(appFolder);
        _settingsPath = Path.Combine(appFolder, SettingsFileName);

        SeedGerman();
        SeedTurkish();
        LoadLanguage();
    }

    public bool IsGerman => CurrentLanguage == UiLanguage.Deutsch;

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        var source = CurrentLanguage == UiLanguage.Deutsch ? _de : _tr;
        if (source.TryGetValue(key, out var value))
            return value;

        if (_de.TryGetValue(key, out var germanValue))
            return germanValue;

        return key;
    }

    public void SetLanguage(UiLanguage language)
    {
        if (CurrentLanguage == language)
            return;

        CurrentLanguage = language;
        SaveLanguage();
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    private void LoadLanguage()
    {
        try
        {
            if (!File.Exists(_settingsPath))
                return;

            var json = File.ReadAllText(_settingsPath);
            var settings = JsonSerializer.Deserialize<LocalizationSettings>(json);
            CurrentLanguage = settings?.Language ?? UiLanguage.Deutsch;
        }
        catch
        {
            CurrentLanguage = UiLanguage.Deutsch;
        }
    }

    private void SaveLanguage()
    {
        try
        {
            var json = JsonSerializer.Serialize(new LocalizationSettings { Language = CurrentLanguage });
            File.WriteAllText(_settingsPath, json);
        }
        catch
        {
            // ignore
        }
    }

    private void SeedGerman()
    {
        Add(_de,
            ("Language.Section", "Sprache"),
            ("Language.Label", "Oberflächensprache"),
            ("Language.German", "Deutsch"),
            ("Language.Turkish", "Türkisch"),
            ("Main.AppSubtitle", "Angebote und Rechnungen in einer übersichtlichen, modernen Arbeitsumgebung verwalten."),
            ("Main.Action.Invoice", "Rechnung"),
            ("Main.Action.GenerateInvoice", "Rechnung Generieren"),
            ("Main.Action.GenerateOffer", "Angebot Generieren"),
            ("Main.Action.Save", "Speichern"),
            ("Main.Action.Offer", "Angebot"),
            ("Main.Sidebar.Workspace", "Arbeitsbereich"),
            ("Main.Sidebar.WorkspaceSubtitle", "Schnellzugriff und aktueller Dokumentstatus"),
            ("Main.Sidebar.ActiveDocument", "Aktives Dokument"),
            ("Main.Sidebar.QuickActions", "Direktaktionen"),
            ("Main.Sidebar.Texts", "Texte"),
            ("Main.Sidebar.Management", "Verwaltung"),
            ("Main.Sidebar.More", "Mehr"),
            ("Main.Sidebar.NewOffer", "Neues Angebot"),
            ("Main.Sidebar.NewInvoice", "Neue Rechnung"),
            ("Main.Sidebar.ConvertOffer", "Angebot in Rechnung umwandeln"),
            ("Main.Sidebar.SendEmail", "Per E-Mail senden"),
            ("Main.Sidebar.OpenArchive", "Archiv öffnen"),
            ("Main.Sidebar.ProfessionalInvoiceText", "Professioneller Rechnungstext"),
            ("Main.Sidebar.OfferTexts", "Angebotstexte"),
            ("Main.Sidebar.CompanyData", "Unternehmensdaten"),
            ("Main.Sidebar.Catalog", "Leistungskatalog / Artikelverwaltung"),
            ("Main.Sidebar.Customers", "Kunden"),
            ("Main.Sidebar.IncomingInvoices", "Eingangsrechnungen / Belegarchiv"),
            ("Main.Sidebar.EmailSettings", "E-Mail-Einstellungen"),
            ("Main.Sidebar.FinanceDashboard", "Finanzübersicht"),
            ("Main.Sidebar.SaveFolder", "Speicherort auswählen"),
            ("Main.Sidebar.ArchiveFolder", "Archivordner festlegen"),
            ("Main.Sidebar.Exit", "Beenden"),
            ("Main.RightSidebar.Title", "Dokumentaktionen"),
            ("Main.RightSidebar.Subtitle", "Schnellzugriff auf die wichtigsten Befehle"),
            ("Main.Placeholder.NoNumber", "Noch keine Dokumentnummer"),
            ("Main.Placeholder.NoCustomer", "Es wurde noch kein Kunde ausgewählt"),
            ("Main.Doc.Invoice", "Rechnung"),
            ("Main.Doc.Offer", "Angebot"),
            ("Main.Title.InvoiceApp", "Rechnungsprogramm"),
            ("Main.Title.OfferApp", "Angebotsprogramm"),
            ("Main.Label.InvoiceNumber", "Rechnungsnummer:"),
            ("Main.Label.OfferNumber", "Angebotsnummer:"),
            ("Main.Label.InvoiceDate", "Rechnungsdatum:"),
            ("Main.Label.OfferDate", "Angebotsdatum:"),
            ("Main.Label.ServiceDate", "Leistungsdatum:"),
            ("Main.Label.TaxNumber", "Steuernummer:"),
            ("Main.Label.VatId", "USt-IdNr:"),
            ("Main.Label.Object", "Objekt:"),
            ("Main.Label.DeliveryTime", "Lieferzeit:"),
            ("Main.Label.Customer", "Kunde:"),
            ("Main.Label.NameCompany", "Name/Firma:"),
            ("Main.Label.Street", "Straße:"),
            ("Main.Label.HouseNumber", "Hausnr.:"),
            ("Main.Label.PostalCode", "PLZ:"),
            ("Main.Label.City", "Stadt:"),
            ("Main.Label.Email", "E-Mail:"),
            ("Main.LinkedReceipts.Title", "Zugeordnete Kostenbelege"),
            ("Main.LinkedReceipts.AssignButton", "Kostenbeleg dieser Rechnung zuordnen"),
            ("Main.LinkedReceipts.OpenButton", "Beleg öffnen"),
            ("Main.LinkedReceipts.RemoveButton", "Zuordnung entfernen"),
            ("Main.LinkedReceipts.Info", "Diese Belege werden mit der Rechnung verknüpft und beim PDF als Folgeseiten mitgespeichert, damit Sie die Ausgaben zu diesem Auftrag später nachvollziehen können."),
            ("Main.LinkedReceipts.MissingInvoiceNumber", "Bitte vergeben oder übernehmen Sie zuerst eine Rechnungsnummer, bevor Sie einen Beleg zuordnen."),
            ("Main.LinkedReceipts.SelectEntryFirst", "Bitte wählen Sie zuerst einen zugeordneten Beleg aus."),
            ("Main.LinkedReceipts.RemoveConfirm", "Die Zuordnung dieses Belegs zu der aktuell ausgewählten Rechnung wird entfernt. Der Beleg selbst bleibt im Archiv erhalten. Möchten Sie fortfahren?"),
            ("Main.LinkedReceipts.RemoveFailed", "Die Zuordnung des Belegs konnte nicht entfernt werden: {0}"),
            ("Main.Check.SmallBusiness", "Kleinunternehmerregelung (§19 UStG) – keine Umsatzsteuer ausweisen"),
            ("Main.Group.Recipient", "Empfänger"),
            ("Main.Group.Positions", "Positionen im PDF-Layout verwalten"),
            ("Main.Button.AddFromCatalog", "Aus Katalog hinzufügen"),
            ("Main.Button.AddPosition", "Position hinzufügen"),
            ("Main.Button.RemoveSelection", "Ausgewählte Position löschen"),
            ("Main.Button.AddNote", "Hinweis ergänzen"),
            ("Main.Button.RemoveNote", "Hinweis entfernen"),
            ("Main.Positions.Title", "POSITIONEN"),
            ("Main.Positions.Info", "Die Bearbeitung erfolgt direkt auf dieser Arbeitsfläche; das erzeugte PDF basiert auf denselben Daten."),
            ("Main.Positions.Note", "Positionsnotiz"),
            ("Main.Totals.Title", "Summen"),
            ("Archive.Title", "Archiv"),
            ("Archive.Refresh", "Aktualisieren"),
            ("Archive.OpenPdf", "PDF öffnen"),
            ("Archive.OpenFolder", "Ordner öffnen"),
            ("Archive.Delete", "Löschen"),
            ("Archive.Edit", "Bearbeiten"),
            ("Archive.Column.Type", "Typ"),
            ("Archive.Column.Number", "Nr."),
            ("Archive.Column.Attachments", "Belege"),
            ("Archive.Column.Status", "Status"),
            ("Archive.Column.Date", "Datum"),
            ("Archive.Column.LastAction", "Letzte Aktion"),
            ("Archive.Column.Customer", "Kunde"),
            ("Archive.Search.Placeholder", "Archiv durchsuchen"),
            ("Archive.Filter.AllTypes", "Alle Typen"),
            ("Archive.Filter.AllStatuses", "Alle Status"),
            ("Archive.Status.Draft", "Entwurf"),
            ("Archive.Status.Preview", "Vorschau"),
            ("Archive.Status.Sent", "Gesendet"),
            ("Archive.Status.Archived", "Archiviert"),
            ("Archive.Status.Paid", "Bezahlt"),
            ("Archive.DeleteConfirmTitle", "Bestätigung"),
            ("Archive.DeleteConfirmMessage", "Der ausgewählte Archiveintrag einschließlich PDF- und JSON-Datei wird dauerhaft entfernt. Möchten Sie fortfahren?"),
            ("Archive.DeleteFailed", "Der Archivdatensatz konnte nicht gelöscht werden."),
            ("Archive.JsonMissing", "Die JSON-Datei wurde nicht gefunden."),
            ("Archive.FormatUnknown", "Das Archivdateiformat wurde nicht erkannt."),
            ("Archive.EntryUnreadable", "Der ausgewählte Archivdatensatz konnte nicht gelesen werden."),
            ("Archive.MainWindowMissing", "Das Hauptfenster wurde nicht gefunden."),
            ("Archive.OpenFailed", "Der Archiveintrag konnte nicht geöffnet werden: {0}"),
            ("Archive.Receipts.Title", "Zugeordnete Belege"),
            ("Archive.Receipts.Header", "Verknüpfte Eingangsbelege"),
            ("Archive.Receipts.Subtitle", "Rechnung {0} enthält aktuell {1} zugeordnete Belege."),
            ("Archive.Receipts.Empty", "Für diese Rechnung sind aktuell keine Belege verknüpft."),
            ("Common.Info", "Information"),
            ("Common.Error", "Fehler"),
            ("Common.Save", "Speichern"),
            ("Common.Cancel", "Abbrechen"),
            ("Common.Close", "Schließen"),
            ("Common.New", "Neu"),
            ("Common.Delete", "Löschen"),
            ("Common.Saved", "Die Änderungen wurden gespeichert."),
            ("Catalog.Title", "Leistungskatalog / Artikelverwaltung"),
            ("Catalog.Detail", "Details"),
            ("Catalog.Column.Number", "Nr."),
            ("Catalog.Column.Name", "Bezeichnung"),
            ("Catalog.Column.Unit", "Einheit"),
            ("Catalog.Column.Price", "Preis"),
            ("Catalog.Column.Tax", "MwSt.%"),
            ("Catalog.Column.Active", "Aktiv"),
            ("Catalog.Label.Number", "Nr.:"),
            ("Catalog.Label.Name", "Bezeichnung:"),
            ("Catalog.Label.Unit", "Einheit:"),
            ("Catalog.Label.Price", "Preis:"),
            ("Catalog.Label.Tax", "MwSt.%:"),
            ("Catalog.Label.Description", "Beschreibung:"),
            ("Customers.Title", "Kunden"),
            ("Customers.Detail", "Kundendetails"),
            ("Customers.Column.Company", "Firma"),
            ("Customers.Column.City", "Stadt"),
            ("Customers.Column.Email", "E-Mail"),
            ("Customers.Label.Company", "Firma:"),
            ("Customers.Label.Street", "Straße:"),
            ("Customers.Label.Number", "Hausnr.:"),
            ("Customers.Label.PostalCode", "PLZ:"),
            ("Customers.Label.City", "Stadt:"),
            ("Customers.Label.Country", "Land:"),
            ("Customers.Label.Email", "E-Mail:"),
            ("Company.Title", "Unternehmensdaten"),
            ("Company.Header", "Unternehmensdaten"),
            ("Company.Label.Name", "Firmenname:"),
            ("Company.Label.Street", "Straße:"),
            ("Company.Label.Number", "Hausnr.:"),
            ("Company.Label.PostalCode", "PLZ:"),
            ("Company.Label.City", "Stadt:"),
            ("Company.Label.Country", "Land:"),
            ("Company.Label.Phone", "Telefon:"),
            ("Company.Label.Email", "E-Mail:"),
            ("Company.Label.Web", "Web:"),
            ("Company.Label.TaxNumber", "Steuernummer:"),
            ("Company.Label.VatId", "USt-IdNr:"),
            ("Company.Label.Logo", "Logo:"),
            ("Company.SelectLogo", "Logo hochladen"),
            ("Company.Label.PaymentTerms", "Zahlungsbedingungen:"),
            ("Company.Label.AccountHolder", "Kontoinhaber:"),
            ("Company.Label.Iban", "IBAN:"),
            ("Company.Label.Bic", "BIC:"),
            ("OfferTexts.Title", "Angebotstexte"),
            ("OfferTexts.Header", "Angebotstexte für die zweite PDF-Seite"),
            ("OfferTexts.Intro", "Einleitung (optional)"),
            ("OfferTexts.Liability", "Hinweis zur Haftungsbegrenzung (optional)"),
            ("OfferTexts.OrderConfirmation", "Auftragsbestätigungstext (optional)"),
            ("OfferTexts.Cancellation", "Widerrufsbelehrung (optional)"),
            ("OfferTexts.Note", "Hinweis: Dieser Abschnitt ist in der Regel nur für B2C-Angebote relevant. Wenn das Feld leer bleibt, wird er im PDF nicht ausgegeben."),
            ("ArticleSelection.Title", "Position aus dem Katalog übernehmen"),
            ("ArticleSelection.Search", "Suche:"),
            ("ArticleSelection.Add", "Hinzufügen"),
            ("EmailSend.Title", "E-Mail senden"),
            ("EmailSend.To", "An:"),
            ("EmailSend.Subject", "Betreff:"),
            ("EmailSend.Message", "Nachricht:"),
            ("EmailSend.Send", "Senden"),
            ("EmailSend.Success", "Die E-Mail wurde erfolgreich versendet."),
            ("EmailSettings.Title", "E-Mail-Einstellungen"),
            ("EmailSettings.User", "Benutzer:"),
            ("EmailSettings.Password", "Passwort:"),
            ("EmailSettings.FromAddress", "Absender-E-Mail:"),
            ("EmailSettings.FromName", "Absendername:"),
            ("EmailSettings.Note", "Hinweis:"),
            ("EmailSettings.NoteText", "Das Kennwort wird lokal im AppData-Verzeichnis als JSON gespeichert. Das Feld kann bei Bedarf leer bleiben."),
            ("IncomingInvoices.Title", "Eingangsrechnungen"),
            ("IncomingInvoices.Import", "Datei importieren"),
            ("IncomingInvoices.Scan", "Scannen"),
            ("IncomingInvoices.OpenDocument", "Dokument öffnen"),
            ("IncomingInvoices.ListTitle", "Archivierte Eingangsrechnungen"),
            ("IncomingInvoices.DetailsTitle", "Belegdetails"),
            ("IncomingInvoices.Column.Supplier", "Lieferant"),
            ("IncomingInvoices.Column.Number", "Rechnungsnr."),
            ("IncomingInvoices.Column.Date", "Datum"),
            ("IncomingInvoices.Column.Gross", "Brutto"),
            ("IncomingInvoices.Column.Project", "Projekt"),
            ("IncomingInvoices.Label.Supplier", "Lieferant:"),
            ("IncomingInvoices.Label.Number", "Rechnungsnr.:"),
            ("IncomingInvoices.Label.Date", "Rechnungsdatum:"),
            ("IncomingInvoices.Label.Net", "Netto:"),
            ("IncomingInvoices.Label.Tax", "MwSt.:"),
            ("IncomingInvoices.Label.Gross", "Brutto:"),
            ("IncomingInvoices.Label.Project", "Projekt / Objekt:"),
            ("IncomingInvoices.Label.Category", "Kategorie:"),
            ("IncomingInvoices.Label.ArchivedInvoiceSelect", "Archivierte Rechnung:"),
            ("IncomingInvoices.Label.AssignedInvoice", "Zugeordnete Rechnung:"),
            ("IncomingInvoices.Label.SuggestedInvoice", "Vorschlag:"),
            ("IncomingInvoices.Label.DetectedSupplier", "Erkannter Lieferant:"),
            ("IncomingInvoices.Label.DetectedInvoiceNumber", "Erkannte Rechnungsnr.:"),
            ("IncomingInvoices.Label.OcrText", "OCR-Text:"),
            ("IncomingInvoices.Label.OriginalFile", "Originaldatei:"),
            ("IncomingInvoices.Label.Note", "Notiz:"),
            ("IncomingInvoices.Analyze", "OCR analysieren"),
            ("IncomingInvoices.OpenOcrFolder", "OCR-Ordner öffnen"),
            ("IncomingInvoices.ImportDialogTitle", "Eingangsrechnung oder Beleg auswählen"),
            ("IncomingInvoices.ImportSuccess", "Das Dokument wurde importiert und archiviert."),
            ("IncomingInvoices.ImportFailed", "Das Dokument konnte nicht importiert werden: {0}"),
            ("IncomingInvoices.ScanInfo", "Die direkte Scanneranbindung ist als nächster Ausbauschritt vorgesehen. Für den Moment können Sie eine gescannte PDF- oder Bilddatei importieren."),
            ("IncomingInvoices.ScanSuccess", "Der Beleg wurde erfolgreich vom Scanner übernommen und archiviert."),
            ("IncomingInvoices.ScanCanceled", "Der Scanvorgang wurde abgebrochen."),
            ("IncomingInvoices.ScanFailed", "Der Scanner konnte nicht verwendet werden: {0}"),
            ("IncomingInvoices.AnalyzeSuccess", "Die OCR-Analyse wurde erfolgreich ausgeführt."),
            ("IncomingInvoices.AnalyzeFailed", "Die OCR-Analyse konnte nicht ausgeführt werden: {0}"),
            ("IncomingInvoices.OcrReady", "OCR ist bereit. PDF-Text wird direkt gelesen, Bilder werden mit Tesseract analysiert."),
            ("IncomingInvoices.OcrMissingData", "Für Bild-OCR fehlen Sprachdateien. Legen Sie deu.traineddata, tur.traineddata oder eng.traineddata hier ab: {0}"),
            ("IncomingInvoices.OpenOcrFolderFailed", "Der OCR-Ordner konnte nicht geöffnet werden: {0}"),
            ("IncomingInvoices.SaveFailed", "Der Beleg konnte nicht gespeichert werden: {0}"),
            ("IncomingInvoices.DeleteConfirm", "Der ausgewählte Beleg wird dauerhaft aus dem Archiv entfernt. Möchten Sie fortfahren?"),
            ("IncomingInvoices.DeleteFailed", "Der Beleg konnte nicht gelöscht werden."),
            ("IncomingInvoices.OpenFailed", "Das Dokument konnte nicht geöffnet werden: {0}"),
            ("IncomingInvoices.OpenFolderFailed", "Der Belegordner konnte nicht geöffnet werden: {0}"),
            ("Finance.Title", "Finanzübersicht"),
            ("Finance.Revenue", "Umsatz"),
            ("Finance.Expenses", "Ausgaben"),
            ("Finance.OpenReceivables", "Noch offen zu erhalten"),
            ("Finance.Profit", "Ergebnis"),
            ("Finance.PaidRevenue", "Bisher verdient"),
            ("Finance.PaidRevenueTax", "Zu zahlende Steuer 20%"),
            ("Finance.TotalPrincipalTax", "Zu zahlende Steuer 20% vom Nettobetrag"),
            ("Finance.TotalInvoiceAmount", "Gesamtsumme aller Rechnungen"),
            ("Finance.LinkedReceiptTotal", "Zugeordnete Kostenbelege Gesamt"),
            ("Finance.InvoiceCount", "Rechnungen gesamt"),
            ("Finance.PaidCount", "Bezahlte Rechnungen"),
            ("Finance.IncomingCount", "Eingangsbelege / Ausgaben"),
            ("Finance.AverageInvoice", "Ø Rechnung"),
            ("Finance.MarkOpen", "Als offen markieren"),
            ("Finance.MarkPaid", "Als bezahlt markieren"),
            ("Finance.ActionOpen", "Als offen markiert"),
            ("Finance.ActionPaid", "Als bezahlt markiert"),
            ("Finance.SelectInvoiceFirst", "Bitte wählen Sie zuerst in der Liste der ausgehenden Dokumente eine Rechnung aus."),
            ("Finance.StatusUpdateFailed", "Der Status der ausgewählten Rechnung konnte nicht aktualisiert werden."),
            ("Finance.OutgoingDocuments", "Ausgehende Dokumente"),
            ("Finance.IncomingDocuments", "Eingangsrechnungen"),
            ("Finance.SelectedInvoice", "Ausgewählte Rechnung"),
            ("Finance.SelectedInvoice.None", "Keine Rechnung ausgewählt"),
            ("Finance.SelectedInvoice.Customer", "Kunde"),
            ("Finance.SelectedInvoice.Date", "Datum"),
            ("Finance.SelectedInvoice.Number", "Rechnungsnummer"),
            ("Finance.SelectedInvoice.Amount", "Betrag dieser Rechnung"),
            ("Finance.SelectedInvoice.Tax", "Zu zahlende Steuer 20%"),
            ("Finance.TaxReserve", "Voraussichtliche Jahressteuer 20%"),
            ("UpdatePrompt.WindowTitle", "Aktualisierung verfügbar"),
            ("UpdatePrompt.Title", "Neue Version gefunden"),
            ("UpdatePrompt.Message", "Version {0} ist verfügbar. Ihre aktuelle Version ist {1}."),
            ("UpdatePrompt.NoNotes", "Für dieses Update liegen keine zusätzlichen Hinweise vor."),
            ("UpdatePrompt.UpdateButton", "Jetzt aktualisieren"),
            ("UpdatePrompt.DownloadFailed", "Das Update konnte nicht heruntergeladen oder gestartet werden: {0}"),
            ("NoteWindow.Title", "Hinweis"),
            ("PdfPreview.Title", "PDF-Vorschau"),
            ("Common.Send", "Senden"));
    }

    private void SeedTurkish()
    {
        Add(_tr,
            ("Language.Section", "Dil"),
            ("Language.Label", "Arayüz dili"),
            ("Language.German", "Almanca"),
            ("Language.Turkish", "Türkçe"),
            ("Main.AppSubtitle", "Teklif ve faturaları sade, modern ve düzenli bir çalışma alanında yönetin."),
            ("Main.Action.Invoice", "Fatura"),
            ("Main.Action.GenerateInvoice", "Fatura Oluştur"),
            ("Main.Action.GenerateOffer", "Teklif Oluştur"),
            ("Main.Action.Save", "Kaydet"),
            ("Main.Action.Offer", "Teklif"),
            ("Main.Sidebar.Workspace", "Çalışma Alanı"),
            ("Main.Sidebar.WorkspaceSubtitle", "Hızlı erişim ve güncel belge durumu"),
            ("Main.Sidebar.ActiveDocument", "Aktif belge"),
            ("Main.Sidebar.QuickActions", "Hızlı aksiyonlar"),
            ("Main.Sidebar.Texts", "Metinler"),
            ("Main.Sidebar.Management", "Yönetim"),
            ("Main.Sidebar.More", "Diğer"),
            ("Main.Sidebar.NewOffer", "Yeni teklif"),
            ("Main.Sidebar.NewInvoice", "Yeni fatura"),
            ("Main.Sidebar.ConvertOffer", "Teklifi faturaya dönüştür"),
            ("Main.Sidebar.SendEmail", "E-posta gönder"),
            ("Main.Sidebar.OpenArchive", "Arşivi aç"),
            ("Main.Sidebar.ProfessionalInvoiceText", "Profesyonel fatura metni"),
            ("Main.Sidebar.OfferTexts", "Teklif metinleri"),
            ("Main.Sidebar.CompanyData", "Şirket bilgileri"),
            ("Main.Sidebar.Catalog", "Hizmet kataloğu / ürün yönetimi"),
            ("Main.Sidebar.Customers", "Müşteriler"),
            ("Main.Sidebar.IncomingInvoices", "Gelen faturalar / belge arşivi"),
            ("Main.Sidebar.EmailSettings", "E-posta ayarları"),
            ("Main.Sidebar.FinanceDashboard", "Finans özeti"),
            ("Main.Sidebar.SaveFolder", "Kayıt konumunu seç"),
            ("Main.Sidebar.ArchiveFolder", "Arşiv klasörünü belirle"),
            ("Main.Sidebar.Exit", "Çıkış"),
            ("Main.RightSidebar.Title", "Belge işlemleri"),
            ("Main.RightSidebar.Subtitle", "En önemli komutlara hızlı erişim"),
            ("Main.Placeholder.NoNumber", "Henüz belge numarası oluşturulmadı"),
            ("Main.Placeholder.NoCustomer", "Henüz bir müşteri seçilmedi"),
            ("Main.Doc.Invoice", "Fatura"),
            ("Main.Doc.Offer", "Teklif"),
            ("Main.Title.InvoiceApp", "Fatura Programı"),
            ("Main.Title.OfferApp", "Teklif Programı"),
            ("Main.Label.InvoiceNumber", "Fatura numarası:"),
            ("Main.Label.OfferNumber", "Teklif numarası:"),
            ("Main.Label.InvoiceDate", "Fatura tarihi:"),
            ("Main.Label.OfferDate", "Teklif tarihi:"),
            ("Main.Label.ServiceDate", "Hizmet tarihi:"),
            ("Main.Label.TaxNumber", "Vergi numarası:"),
            ("Main.Label.VatId", "KDV No:"),
            ("Main.Label.Object", "Konu:"),
            ("Main.Label.DeliveryTime", "Teslim süresi:"),
            ("Main.Label.Customer", "Müşteri:"),
            ("Main.Label.NameCompany", "Ad/Firma:"),
            ("Main.Label.Street", "Sokak:"),
            ("Main.Label.HouseNumber", "No:"),
            ("Main.Label.PostalCode", "Posta kodu:"),
            ("Main.Label.City", "Şehir:"),
            ("Main.Label.Email", "E-posta:"),
            ("Main.LinkedReceipts.Title", "Bağlı masraf belgeleri"),
            ("Main.LinkedReceipts.AssignButton", "Bu faturaya masraf belgesi bağla"),
            ("Main.LinkedReceipts.OpenButton", "Belgeyi aç"),
            ("Main.LinkedReceipts.RemoveButton", "Bağlantıyı kaldır"),
            ("Main.LinkedReceipts.Info", "Buradaki belgeler bu faturaya bağlanır ve PDF kaydında devam sayfaları olarak eklenir; böylece bu iş için hangi masrafları yaptığınızı sonradan görebilirsiniz."),
            ("Main.LinkedReceipts.MissingInvoiceNumber", "Belge bağlamadan önce lütfen bir fatura numarası oluşturun veya girin."),
            ("Main.LinkedReceipts.SelectEntryFirst", "Lütfen önce bağlı bir belge seçin."),
            ("Main.LinkedReceipts.RemoveConfirm", "Bu belgenin seçili faturayla bağlantısı kaldırılacak. Belgenin kendisi arşivde kalır. Devam etmek istiyor musunuz?"),
            ("Main.LinkedReceipts.RemoveFailed", "Belge bağlantısı kaldırılamadı: {0}"),
            ("Main.Check.SmallBusiness", "Küçük işletme kuralı (§19 UStG) – KDV gösterme"),
            ("Main.Group.Recipient", "Alıcı"),
            ("Main.Group.Positions", "Pozisyonları PDF düzeninde yönetin"),
            ("Main.Button.AddFromCatalog", "Katalogdan ekle"),
            ("Main.Button.AddPosition", "Pozisyon ekle"),
            ("Main.Button.RemoveSelection", "Seçili pozisyonu sil"),
            ("Main.Button.AddNote", "Not ekle"),
            ("Main.Button.RemoveNote", "Notu kaldır"),
            ("Main.Positions.Title", "POZİSYONLAR"),
            ("Main.Positions.Info", "Düzenleme doğrudan bu çalışma alanında yapılır; oluşturulan PDF aynı verileri esas alır."),
            ("Main.Positions.Note", "Pozisyon notu"),
            ("Main.Totals.Title", "Toplamlar"),
            ("Archive.Title", "Arşiv"),
            ("Archive.Refresh", "Yenile"),
            ("Archive.OpenPdf", "PDF Aç"),
            ("Archive.OpenFolder", "Klasörü Aç"),
            ("Archive.Delete", "Sil"),
            ("Archive.Edit", "Düzenle"),
            ("Archive.Column.Type", "Tür"),
            ("Archive.Column.Number", "No"),
            ("Archive.Column.Attachments", "Ek belge"),
            ("Archive.Column.Status", "Durum"),
            ("Archive.Column.Date", "Tarih"),
            ("Archive.Column.LastAction", "Son işlem"),
            ("Archive.Column.Customer", "Müşteri"),
            ("Archive.Search.Placeholder", "Arşivde ara"),
            ("Archive.Filter.AllTypes", "Tüm türler"),
            ("Archive.Filter.AllStatuses", "Tüm durumlar"),
            ("Archive.Status.Draft", "Taslak"),
            ("Archive.Status.Preview", "Önizleme"),
            ("Archive.Status.Sent", "Gönderildi"),
            ("Archive.Status.Archived", "Arşivlendi"),
            ("Archive.Status.Paid", "Ödendi"),
            ("Archive.DeleteConfirmTitle", "Onay"),
            ("Archive.DeleteConfirmMessage", "Seçili arşiv kaydı, PDF ve JSON dosyalarıyla birlikte kalıcı olarak silinecektir. Devam etmek istiyor musunuz?"),
            ("Archive.DeleteFailed", "Arşiv kaydı silinemedi."),
            ("Archive.JsonMissing", "JSON dosyası bulunamadı."),
            ("Archive.FormatUnknown", "Arşiv dosyası formatı tanınmadı."),
            ("Archive.EntryUnreadable", "Seçilen arşiv kaydı okunamadı."),
            ("Archive.MainWindowMissing", "Ana pencere bulunamadı."),
            ("Archive.OpenFailed", "Arşiv kaydı açılamadı: {0}"),
            ("Archive.Receipts.Title", "Bağlı belgeler"),
            ("Archive.Receipts.Header", "Bağlı gider belgeleri"),
            ("Archive.Receipts.Subtitle", "{0} numaralı faturaya şu anda {1} belge bağlı."),
            ("Archive.Receipts.Empty", "Bu faturaya şu anda bağlı belge yok."),
            ("Finance.SelectedInvoice", "Seçilen fatura"),
            ("Finance.SelectedInvoice.None", "Fatura seçilmedi"),
            ("Finance.SelectedInvoice.Customer", "Müşteri"),
            ("Finance.SelectedInvoice.Date", "Tarih"),
            ("Finance.SelectedInvoice.Number", "Fatura no"),
            ("Finance.SelectedInvoice.Amount", "Bu faturanın tutarı"),
            ("Finance.SelectedInvoice.Tax", "Bu fatura için ödenecek vergi %20"),
            ("Finance.TaxReserve", "Tahmini yıl sonu ödenecek vergi %20"),
            ("UpdatePrompt.WindowTitle", "Güncelleme mevcut"),
            ("UpdatePrompt.Title", "Yeni sürüm bulundu"),
            ("UpdatePrompt.Message", "{0} sürümü mevcut. Şu an kullandığınız sürüm {1}."),
            ("UpdatePrompt.NoNotes", "Bu güncelleme için ek not bulunmuyor."),
            ("UpdatePrompt.UpdateButton", "Güncelle"),
            ("UpdatePrompt.DownloadFailed", "Güncelleme indirilemedi veya başlatılamadı: {0}"),
            ("Common.Info", "Bilgi"),
            ("Common.Error", "Hata"),
            ("Common.Save", "Kaydet"),
            ("Common.Cancel", "İptal"),
            ("Common.Close", "Kapat"),
            ("Common.New", "Yeni"),
            ("Common.Delete", "Sil"),
            ("Common.Saved", "Değişiklikler başarıyla kaydedildi."),
            ("Catalog.Title", "Hizmet kataloğu / ürün yönetimi"),
            ("Catalog.Detail", "Detay"),
            ("Catalog.Column.Number", "No"),
            ("Catalog.Column.Name", "Ad"),
            ("Catalog.Column.Unit", "Birim"),
            ("Catalog.Column.Price", "Fiyat"),
            ("Catalog.Column.Tax", "KDV %"),
            ("Catalog.Column.Active", "Aktif"),
            ("Catalog.Label.Number", "No:"),
            ("Catalog.Label.Name", "Ad:"),
            ("Catalog.Label.Unit", "Birim:"),
            ("Catalog.Label.Price", "Fiyat:"),
            ("Catalog.Label.Tax", "KDV %:"),
            ("Catalog.Label.Description", "Açıklama:"),
            ("Customers.Title", "Müşteriler"),
            ("Customers.Detail", "Müşteri detayları"),
            ("Customers.Column.Company", "Firma"),
            ("Customers.Column.City", "Şehir"),
            ("Customers.Column.Email", "E-posta"),
            ("Customers.Label.Company", "Firma:"),
            ("Customers.Label.Street", "Sokak:"),
            ("Customers.Label.Number", "No:"),
            ("Customers.Label.PostalCode", "Posta kodu:"),
            ("Customers.Label.City", "Şehir:"),
            ("Customers.Label.Country", "Ülke:"),
            ("Customers.Label.Email", "E-posta:"),
            ("Company.Title", "Şirket Bilgileri"),
            ("Company.Header", "Şirket Bilgileri"),
            ("Company.Label.Name", "Firma adı:"),
            ("Company.Label.Street", "Sokak:"),
            ("Company.Label.Number", "No:"),
            ("Company.Label.PostalCode", "Posta kodu:"),
            ("Company.Label.City", "Şehir:"),
            ("Company.Label.Country", "Ülke:"),
            ("Company.Label.Phone", "Telefon:"),
            ("Company.Label.Email", "E-posta:"),
            ("Company.Label.Web", "Web:"),
            ("Company.Label.TaxNumber", "Vergi numarası:"),
            ("Company.Label.VatId", "KDV No:"),
            ("Company.Label.Logo", "Logo:"),
            ("Company.SelectLogo", "Logo yükle"),
            ("Company.Label.PaymentTerms", "Ödeme şartı:"),
            ("Company.Label.AccountHolder", "Kontoinhaber:"),
            ("Company.Label.Iban", "IBAN:"),
            ("Company.Label.Bic", "BIC:"),
            ("OfferTexts.Title", "Teklif metinleri"),
            ("OfferTexts.Header", "PDF teklifinin ikinci sayfası için metinler"),
            ("OfferTexts.Intro", "Giriş (isteğe bağlı)"),
            ("OfferTexts.Liability", "Sorumluluk sınırı bilgilendirmesi (isteğe bağlı)"),
            ("OfferTexts.OrderConfirmation", "Sipariş onay metni (isteğe bağlı)"),
            ("OfferTexts.Cancellation", "Cayma bilgilendirmesi (isteğe bağlı)"),
            ("OfferTexts.Note", "Not: Bu bölüm genellikle yalnızca B2C (tüketici) tekliflerinde gereklidir. Alan boş bırakılırsa PDF'te gösterilmez."),
            ("ArticleSelection.Title", "Katalogdan pozisyon ekle"),
            ("ArticleSelection.Search", "Ara:"),
            ("ArticleSelection.Add", "Ekle"),
            ("EmailSend.Title", "E-posta Gönder"),
            ("EmailSend.To", "Kime:"),
            ("EmailSend.Subject", "Konu:"),
            ("EmailSend.Message", "Mesaj:"),
            ("EmailSend.Send", "Gönder"),
            ("EmailSend.Success", "E-posta başarıyla gönderildi."),
            ("EmailSettings.Title", "E-posta Ayarları"),
            ("EmailSettings.User", "Kullanıcı:"),
            ("EmailSettings.Password", "Şifre:"),
            ("EmailSettings.FromAddress", "Gönderen e-posta:"),
            ("EmailSettings.FromName", "Gönderen adı:"),
            ("EmailSettings.Note", "Not:"),
            ("EmailSettings.NoteText", "Parola AppData klasöründe JSON formatında yerel olarak saklanır. Gerekirse alanı boş bırakabilirsiniz."),
            ("IncomingInvoices.Title", "Gelen Faturalar"),
            ("IncomingInvoices.Import", "Dosya içe aktar"),
            ("IncomingInvoices.Scan", "Tara"),
            ("IncomingInvoices.OpenDocument", "Belgeyi aç"),
            ("IncomingInvoices.ListTitle", "Arşivlenen gelen faturalar"),
            ("IncomingInvoices.DetailsTitle", "Belge detayları"),
            ("IncomingInvoices.Column.Supplier", "Tedarikçi"),
            ("IncomingInvoices.Column.Number", "Fatura no"),
            ("IncomingInvoices.Column.Date", "Tarih"),
            ("IncomingInvoices.Column.Gross", "Brüt"),
            ("IncomingInvoices.Column.Project", "Proje"),
            ("IncomingInvoices.Label.Supplier", "Tedarikçi:"),
            ("IncomingInvoices.Label.Number", "Fatura no:"),
            ("IncomingInvoices.Label.Date", "Fatura tarihi:"),
            ("IncomingInvoices.Label.Net", "Net:"),
            ("IncomingInvoices.Label.Tax", "KDV:"),
            ("IncomingInvoices.Label.Gross", "Brüt:"),
            ("IncomingInvoices.Label.Project", "Proje / Obje:"),
            ("IncomingInvoices.Label.Category", "Kategori:"),
            ("IncomingInvoices.Label.ArchivedInvoiceSelect", "Arşivdeki fatura:"),
            ("IncomingInvoices.Label.AssignedInvoice", "Bağlı fatura:"),
            ("IncomingInvoices.Label.SuggestedInvoice", "Öneri:"),
            ("IncomingInvoices.Label.DetectedSupplier", "Algılanan tedarikçi:"),
            ("IncomingInvoices.Label.DetectedInvoiceNumber", "Algılanan fatura no:"),
            ("IncomingInvoices.Label.OcrText", "OCR metni:"),
            ("IncomingInvoices.Label.OriginalFile", "Orijinal dosya:"),
            ("IncomingInvoices.Label.Note", "Not:"),
            ("IncomingInvoices.Analyze", "OCR analiz et"),
            ("IncomingInvoices.OpenOcrFolder", "OCR klasörünü aç"),
            ("IncomingInvoices.ImportDialogTitle", "Gelen fatura veya belge seçin"),
            ("IncomingInvoices.ImportSuccess", "Belge içe aktarıldı ve arşivlendi."),
            ("IncomingInvoices.ImportFailed", "Belge içe aktarılamadı: {0}"),
            ("IncomingInvoices.ScanInfo", "Doğrudan tarayıcı bağlantısı bir sonraki geliştirme adımı için hazırlandı. Şimdilik taranmış PDF veya görsel dosyası içe aktarabilirsiniz."),
            ("IncomingInvoices.ScanSuccess", "Belge tarayıcıdan başarıyla alındı ve arşivlendi."),
            ("IncomingInvoices.ScanCanceled", "Tarama işlemi iptal edildi."),
            ("IncomingInvoices.ScanFailed", "Tarayıcı kullanılamadı: {0}"),
            ("IncomingInvoices.AnalyzeSuccess", "OCR analizi başarıyla tamamlandı."),
            ("IncomingInvoices.AnalyzeFailed", "OCR analizi çalıştırılamadı: {0}"),
            ("IncomingInvoices.OcrReady", "OCR hazır. PDF metni doğrudan okunur, görseller Tesseract ile analiz edilir."),
            ("IncomingInvoices.OcrMissingData", "Görsel OCR için dil dosyaları eksik. deu.traineddata, tur.traineddata veya eng.traineddata dosyalarını şu klasöre koyun: {0}"),
            ("IncomingInvoices.OpenOcrFolderFailed", "OCR klasörü açılamadı: {0}"),
            ("IncomingInvoices.SaveFailed", "Belge kaydedilemedi: {0}"),
            ("IncomingInvoices.DeleteConfirm", "Seçili belge arşivden kalıcı olarak silinecek. Devam etmek istiyor musunuz?"),
            ("IncomingInvoices.DeleteFailed", "Belge silinemedi."),
            ("IncomingInvoices.OpenFailed", "Belge açılamadı: {0}"),
            ("IncomingInvoices.OpenFolderFailed", "Belge klasörü açılamadı: {0}"),
            ("Finance.Title", "Finans özeti"),
            ("Finance.Revenue", "Gelir"),
            ("Finance.Expenses", "Gider"),
            ("Finance.OpenReceivables", "Açık alacaklar"),
            ("Finance.Profit", "Sonuç"),
            ("Finance.LinkedReceiptTotal", "Bağlı gider faturaları toplamı"),
            ("Finance.InvoiceCount", "Faturalar"),
            ("Finance.PaidCount", "Ödenenler"),
            ("Finance.IncomingCount", "Gelen belgeler"),
            ("Finance.AverageInvoice", "Ort. fatura"),
            ("Finance.MarkOpen", "Açık olarak işaretle"),
            ("Finance.MarkPaid", "Ödendi olarak işaretle"),
            ("Finance.ActionOpen", "Açık olarak işaretlendi"),
            ("Finance.ActionPaid", "Ödendi olarak işaretlendi"),
            ("Finance.SelectInvoiceFirst", "Lütfen önce giden belgeler listesinden bir fatura seçin."),
            ("Finance.StatusUpdateFailed", "Seçilen faturanın durumu güncellenemedi."),
            ("Finance.OutgoingDocuments", "Giden belgeler"),
            ("Finance.IncomingDocuments", "Gelen faturalar"),
            ("NoteWindow.Title", "Not"),
            ("PdfPreview.Title", "PDF Önizleme"),
            ("Common.Send", "Gönder"));
    }

    private static void Add(Dictionary<string, string> target, params (string Key, string Value)[] entries)
    {
        foreach (var (key, value) in entries)
            target[key] = value;
    }

    private sealed class LocalizationSettings
    {
        public UiLanguage Language { get; set; } = UiLanguage.Deutsch;
    }
}
